name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: Hey, thanks for helping to contribute to Neu UI. For any further information about how to contribute then please take a look at the docs https://ui-neu.netlify.app/
        pr-message: Hey, congratulations on your first PR to Neu UI 🎉. Thanks for helping to contribute. We're working to get to this as soon as possible so bear with us, it may take up to a couple of days for someone to come back with feedback.
